PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS "scores";
DROP TABLE IF EXISTS "events";
DROP TABLE IF EXISTS "teams";
DROP TABLE IF EXISTS "clubs";
DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
	"id" INTEGER PRIMARY KEY,
	"name" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL
);

CREATE TABLE "clubs" (
	"id" INTEGER PRIMARY KEY,
	"name" TEXT NOT NULL UNIQUE
);

CREATE TABLE "teams" (
	"id" INTEGER PRIMARY KEY,
	"club" INTEGER NOT NULL REFERENCES "clubs" ON UPDATE CASCADE ON DELETE CASCADE,
	"name" TEXT NOT NULL,
	UNIQUE("club", "name") ON CONFLICT ABORT
);

CREATE TABLE "events" (
	"id" INTEGER PRIMARY KEY,
	"name" TEXT NOT NULL UNIQUE,
	"overall_point_multiplier" REAL NOT NULL DEFAULT 1
);

CREATE TABLE "scores" (
	"team" INTEGER NOT NULL REFERENCES "teams" ON UPDATE CASCADE ON DELETE CASCADE,
	"event" INTEGER NOT NULL REFERENCES "events" ON UPDATE CASCADE ON DELETE CASCADE,
	"points" REAL NOT NULL,
	PRIMARY KEY ("team", "event") ON CONFLICT REPLACE
);

COMMIT TRANSACTION;
